name: Release Patch Version

on:
  workflow_dispatch
permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: HighQualityIPCGenerator

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Install .NET Version CLI
      run: dotnet tool install dotnet-version-cli

    - name: Bump patch version and commit
      run: 'dotnet version -f HighQualityIPCGenerator/HighQualityIPCGenerator.csproj patch -m "CI: Bumps patch version for release $newVer."'

    - name: Download Dalamud
      run: curl --output latest.zip -L "https://goatcorp.github.io/dalamud-distrib/latest.zip"

    - name: Extract Dalamud
      run: unzip latest.zip -d /home/runner/dalamud-distrib

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release
      env:
        DALAMUD_HOME: /home/runner/dalamud-distrib

    - name: Push versioning commit
      run: git push && git push --tags

    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HQIPC
        path: ./HighQualityIPCGenerator/bin/x64/Release/*
        if-no-files-found: error
        retention-days: 7

